name: Run Selenium Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.4.3

    - name: Setup Node.js
      uses: actions/setup-node@v2.5.0
      with:
        node-version: '14.18.3'

    - name: Install dependencies
      run: npm install

    - name: Run Selenium Tests
      run: npm test