name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configuração do Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.18.3

      - name: Verificar versão do Chrome
        run: google-chrome --version

      - name: Instalação das dependências
        run: npm install

      - name: Instalar Chrome
        run: sudo dpkg -i ChromeStandaloneSetup64.exe 

      - name: Execução dos testes
        run: npm test